// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc.proto

package mykvstoreserverpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchCreateRequest_FilterType int32

const (
	WatchCreateRequest_NOPUT    WatchCreateRequest_FilterType = 0
	WatchCreateRequest_NODELETE WatchCreateRequest_FilterType = 1
)

// Enum value maps for WatchCreateRequest_FilterType.
var (
	WatchCreateRequest_FilterType_name = map[int32]string{
		0: "NOPUT",
		1: "NODELETE",
	}
	WatchCreateRequest_FilterType_value = map[string]int32{
		"NOPUT":    0,
		"NODELETE": 1,
	}
)

func (x WatchCreateRequest_FilterType) Enum() *WatchCreateRequest_FilterType {
	p := new(WatchCreateRequest_FilterType)
	*p = x
	return p
}

func (x WatchCreateRequest_FilterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchCreateRequest_FilterType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_enumTypes[0].Descriptor()
}

func (WatchCreateRequest_FilterType) Type() protoreflect.EnumType {
	return &file_rpc_proto_enumTypes[0]
}

func (x WatchCreateRequest_FilterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchCreateRequest_FilterType.Descriptor instead.
func (WatchCreateRequest_FilterType) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{5, 0}
}

type Event_EventType int32

const (
	Event_PUT    Event_EventType = 0
	Event_DELETE Event_EventType = 1
)

// Enum value maps for Event_EventType.
var (
	Event_EventType_name = map[int32]string{
		0: "PUT",
		1: "DELETE",
	}
	Event_EventType_value = map[string]int32{
		"PUT":    0,
		"DELETE": 1,
	}
)

func (x Event_EventType) Enum() *Event_EventType {
	p := new(Event_EventType)
	*p = x
	return p
}

func (x Event_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_enumTypes[1].Descriptor()
}

func (Event_EventType) Type() protoreflect.EnumType {
	return &file_rpc_proto_enumTypes[1]
}

func (x Event_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_EventType.Descriptor instead.
func (Event_EventType) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{9, 0}
}

type ResponseHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     uint64                 `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	MemberId      uint64                 `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Revision      int64                  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	RaftTerm      int64                  `protobuf:"varint,4,opt,name=raft_term,json=raftTerm,proto3" json:"raft_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	mi := &file_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseHeader) GetClusterId() uint64 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *ResponseHeader) GetMemberId() uint64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *ResponseHeader) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ResponseHeader) GetRaftTerm() int64 {
	if x != nil {
		return x.RaftTerm
	}
	return 0
}

type KeyValue struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	CreateRevision int64                  `protobuf:"varint,2,opt,name=create_revision,json=createRevision,proto3" json:"create_revision,omitempty"`
	ModRevision    int64                  `protobuf:"varint,3,opt,name=mod_revision,json=modRevision,proto3" json:"mod_revision,omitempty"`
	Version        int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Value          []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *KeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValue) GetCreateRevision() int64 {
	if x != nil {
		return x.CreateRevision
	}
	return 0
}

func (x *KeyValue) GetModRevision() int64 {
	if x != nil {
		return x.ModRevision
	}
	return 0
}

func (x *KeyValue) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	PrevKv        bool                   `protobuf:"varint,4,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"`
	Lease         int64                  `protobuf:"varint,5,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetPrevKv() bool {
	if x != nil {
		return x.PrevKv
	}
	return false
}

func (x *PutRequest) GetLease() int64 {
	if x != nil {
		return x.Lease
	}
	return 0
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	PrevKv        *KeyValue              `protobuf:"bytes,2,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *PutResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PutResponse) GetPrevKv() *KeyValue {
	if x != nil {
		return x.PrevKv
	}
	return nil
}

type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestUnion:
	//
	//	*WatchRequest_CreateRequest
	//	*WatchRequest_CancelRequest
	//	*WatchRequest_ProgressRequest
	RequestUnion  isWatchRequest_RequestUnion `protobuf_oneof:"request_union"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *WatchRequest) GetRequestUnion() isWatchRequest_RequestUnion {
	if x != nil {
		return x.RequestUnion
	}
	return nil
}

func (x *WatchRequest) GetCreateRequest() *WatchCreateRequest {
	if x != nil {
		if x, ok := x.RequestUnion.(*WatchRequest_CreateRequest); ok {
			return x.CreateRequest
		}
	}
	return nil
}

func (x *WatchRequest) GetCancelRequest() *WatchCancelRequest {
	if x != nil {
		if x, ok := x.RequestUnion.(*WatchRequest_CancelRequest); ok {
			return x.CancelRequest
		}
	}
	return nil
}

func (x *WatchRequest) GetProgressRequest() *WatchProgressRequest {
	if x != nil {
		if x, ok := x.RequestUnion.(*WatchRequest_ProgressRequest); ok {
			return x.ProgressRequest
		}
	}
	return nil
}

type isWatchRequest_RequestUnion interface {
	isWatchRequest_RequestUnion()
}

type WatchRequest_CreateRequest struct {
	CreateRequest *WatchCreateRequest `protobuf:"bytes,1,opt,name=create_request,json=createRequest,proto3,oneof"`
}

type WatchRequest_CancelRequest struct {
	CancelRequest *WatchCancelRequest `protobuf:"bytes,2,opt,name=cancel_request,json=cancelRequest,proto3,oneof"`
}

type WatchRequest_ProgressRequest struct {
	ProgressRequest *WatchProgressRequest `protobuf:"bytes,3,opt,name=progress_request,json=progressRequest,proto3,oneof"`
}

func (*WatchRequest_CreateRequest) isWatchRequest_RequestUnion() {}

func (*WatchRequest_CancelRequest) isWatchRequest_RequestUnion() {}

func (*WatchRequest_ProgressRequest) isWatchRequest_RequestUnion() {}

type WatchCreateRequest struct {
	state          protoimpl.MessageState          `protogen:"open.v1"`
	Key            []byte                          `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RangeEnd       []byte                          `protobuf:"bytes,2,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	StartRevision  int64                           `protobuf:"varint,3,opt,name=start_revision,json=startRevision,proto3" json:"start_revision,omitempty"`
	ProgressNotify bool                            `protobuf:"varint,4,opt,name=progress_notify,json=progressNotify,proto3" json:"progress_notify,omitempty"`
	Filters        []WatchCreateRequest_FilterType `protobuf:"varint,5,rep,packed,name=filters,proto3,enum=mykvstoreserverpb.WatchCreateRequest_FilterType" json:"filters,omitempty"`
	PrevKv         bool                            `protobuf:"varint,6,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"`
	WatchId        int64                           `protobuf:"varint,7,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	Fragment       bool                            `protobuf:"varint,8,opt,name=fragment,proto3" json:"fragment,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchCreateRequest) Reset() {
	*x = WatchCreateRequest{}
	mi := &file_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCreateRequest) ProtoMessage() {}

func (x *WatchCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCreateRequest.ProtoReflect.Descriptor instead.
func (*WatchCreateRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *WatchCreateRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *WatchCreateRequest) GetRangeEnd() []byte {
	if x != nil {
		return x.RangeEnd
	}
	return nil
}

func (x *WatchCreateRequest) GetStartRevision() int64 {
	if x != nil {
		return x.StartRevision
	}
	return 0
}

func (x *WatchCreateRequest) GetProgressNotify() bool {
	if x != nil {
		return x.ProgressNotify
	}
	return false
}

func (x *WatchCreateRequest) GetFilters() []WatchCreateRequest_FilterType {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *WatchCreateRequest) GetPrevKv() bool {
	if x != nil {
		return x.PrevKv
	}
	return false
}

func (x *WatchCreateRequest) GetWatchId() int64 {
	if x != nil {
		return x.WatchId
	}
	return 0
}

func (x *WatchCreateRequest) GetFragment() bool {
	if x != nil {
		return x.Fragment
	}
	return false
}

type WatchCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WatchId       int64                  `protobuf:"varint,1,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchCancelRequest) Reset() {
	*x = WatchCancelRequest{}
	mi := &file_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCancelRequest) ProtoMessage() {}

func (x *WatchCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCancelRequest.ProtoReflect.Descriptor instead.
func (*WatchCancelRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *WatchCancelRequest) GetWatchId() int64 {
	if x != nil {
		return x.WatchId
	}
	return 0
}

type WatchProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchProgressRequest) Reset() {
	*x = WatchProgressRequest{}
	mi := &file_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchProgressRequest) ProtoMessage() {}

func (x *WatchProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchProgressRequest.ProtoReflect.Descriptor instead.
func (*WatchProgressRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{7}
}

type WatchResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Header          *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	WatchId         int64                  `protobuf:"varint,2,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	Created         bool                   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Canceled        bool                   `protobuf:"varint,4,opt,name=canceled,proto3" json:"canceled,omitempty"`
	CompactRevision int64                  `protobuf:"varint,5,opt,name=compact_revision,json=compactRevision,proto3" json:"compact_revision,omitempty"`
	CancelReason    string                 `protobuf:"bytes,6,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
	Fragment        bool                   `protobuf:"varint,7,opt,name=fragment,proto3" json:"fragment,omitempty"`
	Events          []*Event               `protobuf:"bytes,8,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *WatchResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *WatchResponse) GetWatchId() int64 {
	if x != nil {
		return x.WatchId
	}
	return 0
}

func (x *WatchResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *WatchResponse) GetCanceled() bool {
	if x != nil {
		return x.Canceled
	}
	return false
}

func (x *WatchResponse) GetCompactRevision() int64 {
	if x != nil {
		return x.CompactRevision
	}
	return 0
}

func (x *WatchResponse) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

func (x *WatchResponse) GetFragment() bool {
	if x != nil {
		return x.Fragment
	}
	return false
}

func (x *WatchResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Event_EventType        `protobuf:"varint,1,opt,name=type,proto3,enum=mykvstoreserverpb.Event_EventType" json:"type,omitempty"`
	Kv            *KeyValue              `protobuf:"bytes,2,opt,name=kv,proto3" json:"kv,omitempty"`
	PrevKv        *KeyValue              `protobuf:"bytes,3,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *Event) GetType() Event_EventType {
	if x != nil {
		return x.Type
	}
	return Event_PUT
}

func (x *Event) GetKv() *KeyValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

func (x *Event) GetPrevKv() *KeyValue {
	if x != nil {
		return x.PrevKv
	}
	return nil
}

var File_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rawDesc = "" +
	"\n" +
	"\trpc.proto\x12\x11mykvstoreserverpb\"\x85\x01\n" +
	"\x0eResponseHeader\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\x04R\tclusterId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\x04R\bmemberId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\x12\x1b\n" +
	"\traft_term\x18\x04 \x01(\x03R\braftTerm\"\x98\x01\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12'\n" +
	"\x0fcreate_revision\x18\x02 \x01(\x03R\x0ecreateRevision\x12!\n" +
	"\fmod_revision\x18\x03 \x01(\x03R\vmodRevision\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\"c\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x17\n" +
	"\aprev_kv\x18\x04 \x01(\bR\x06prevKv\x12\x14\n" +
	"\x05lease\x18\x05 \x01(\x03R\x05lease\"~\n" +
	"\vPutResponse\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.mykvstoreserverpb.ResponseHeaderR\x06header\x124\n" +
	"\aprev_kv\x18\x02 \x01(\v2\x1b.mykvstoreserverpb.KeyValueR\x06prevKv\"\x95\x02\n" +
	"\fWatchRequest\x12N\n" +
	"\x0ecreate_request\x18\x01 \x01(\v2%.mykvstoreserverpb.WatchCreateRequestH\x00R\rcreateRequest\x12N\n" +
	"\x0ecancel_request\x18\x02 \x01(\v2%.mykvstoreserverpb.WatchCancelRequestH\x00R\rcancelRequest\x12T\n" +
	"\x10progress_request\x18\x03 \x01(\v2'.mykvstoreserverpb.WatchProgressRequestH\x00R\x0fprogressRequestB\x0f\n" +
	"\rrequest_union\"\xd6\x02\n" +
	"\x12WatchCreateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1b\n" +
	"\trange_end\x18\x02 \x01(\fR\brangeEnd\x12%\n" +
	"\x0estart_revision\x18\x03 \x01(\x03R\rstartRevision\x12'\n" +
	"\x0fprogress_notify\x18\x04 \x01(\bR\x0eprogressNotify\x12J\n" +
	"\afilters\x18\x05 \x03(\x0e20.mykvstoreserverpb.WatchCreateRequest.FilterTypeR\afilters\x12\x17\n" +
	"\aprev_kv\x18\x06 \x01(\bR\x06prevKv\x12\x19\n" +
	"\bwatch_id\x18\a \x01(\x03R\awatchId\x12\x1a\n" +
	"\bfragment\x18\b \x01(\bR\bfragment\"%\n" +
	"\n" +
	"FilterType\x12\t\n" +
	"\x05NOPUT\x10\x00\x12\f\n" +
	"\bNODELETE\x10\x01\"/\n" +
	"\x12WatchCancelRequest\x12\x19\n" +
	"\bwatch_id\x18\x01 \x01(\x03R\awatchId\"\x16\n" +
	"\x14WatchProgressRequest\"\xb9\x02\n" +
	"\rWatchResponse\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.mykvstoreserverpb.ResponseHeaderR\x06header\x12\x19\n" +
	"\bwatch_id\x18\x02 \x01(\x03R\awatchId\x12\x18\n" +
	"\acreated\x18\x03 \x01(\bR\acreated\x12\x1a\n" +
	"\bcanceled\x18\x04 \x01(\bR\bcanceled\x12)\n" +
	"\x10compact_revision\x18\x05 \x01(\x03R\x0fcompactRevision\x12#\n" +
	"\rcancel_reason\x18\x06 \x01(\tR\fcancelReason\x12\x1a\n" +
	"\bfragment\x18\a \x01(\bR\bfragment\x120\n" +
	"\x06events\x18\b \x03(\v2\x18.mykvstoreserverpb.EventR\x06events\"\xc4\x01\n" +
	"\x05Event\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".mykvstoreserverpb.Event.EventTypeR\x04type\x12+\n" +
	"\x02kv\x18\x02 \x01(\v2\x1b.mykvstoreserverpb.KeyValueR\x02kv\x124\n" +
	"\aprev_kv\x18\x03 \x01(\v2\x1b.mykvstoreserverpb.KeyValueR\x06prevKv\" \n" +
	"\tEventType\x12\a\n" +
	"\x03PUT\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x012L\n" +
	"\x02KV\x12F\n" +
	"\x03Put\x12\x1d.mykvstoreserverpb.PutRequest\x1a\x1e.mykvstoreserverpb.PutResponse\"\x002Y\n" +
	"\x05Watch\x12P\n" +
	"\x05Watch\x12\x1f.mykvstoreserverpb.WatchRequest\x1a .mykvstoreserverpb.WatchResponse\"\x00(\x010\x01B\x16Z\x14./;mykvstoreserverpbb\x06proto3"

var (
	file_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rawDescData []byte
)

func file_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)))
	})
	return file_rpc_proto_rawDescData
}

var file_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rpc_proto_goTypes = []any{
	(WatchCreateRequest_FilterType)(0), // 0: mykvstoreserverpb.WatchCreateRequest.FilterType
	(Event_EventType)(0),               // 1: mykvstoreserverpb.Event.EventType
	(*ResponseHeader)(nil),             // 2: mykvstoreserverpb.ResponseHeader
	(*KeyValue)(nil),                   // 3: mykvstoreserverpb.KeyValue
	(*PutRequest)(nil),                 // 4: mykvstoreserverpb.PutRequest
	(*PutResponse)(nil),                // 5: mykvstoreserverpb.PutResponse
	(*WatchRequest)(nil),               // 6: mykvstoreserverpb.WatchRequest
	(*WatchCreateRequest)(nil),         // 7: mykvstoreserverpb.WatchCreateRequest
	(*WatchCancelRequest)(nil),         // 8: mykvstoreserverpb.WatchCancelRequest
	(*WatchProgressRequest)(nil),       // 9: mykvstoreserverpb.WatchProgressRequest
	(*WatchResponse)(nil),              // 10: mykvstoreserverpb.WatchResponse
	(*Event)(nil),                      // 11: mykvstoreserverpb.Event
}
var file_rpc_proto_depIdxs = []int32{
	2,  // 0: mykvstoreserverpb.PutResponse.header:type_name -> mykvstoreserverpb.ResponseHeader
	3,  // 1: mykvstoreserverpb.PutResponse.prev_kv:type_name -> mykvstoreserverpb.KeyValue
	7,  // 2: mykvstoreserverpb.WatchRequest.create_request:type_name -> mykvstoreserverpb.WatchCreateRequest
	8,  // 3: mykvstoreserverpb.WatchRequest.cancel_request:type_name -> mykvstoreserverpb.WatchCancelRequest
	9,  // 4: mykvstoreserverpb.WatchRequest.progress_request:type_name -> mykvstoreserverpb.WatchProgressRequest
	0,  // 5: mykvstoreserverpb.WatchCreateRequest.filters:type_name -> mykvstoreserverpb.WatchCreateRequest.FilterType
	2,  // 6: mykvstoreserverpb.WatchResponse.header:type_name -> mykvstoreserverpb.ResponseHeader
	11, // 7: mykvstoreserverpb.WatchResponse.events:type_name -> mykvstoreserverpb.Event
	1,  // 8: mykvstoreserverpb.Event.type:type_name -> mykvstoreserverpb.Event.EventType
	3,  // 9: mykvstoreserverpb.Event.kv:type_name -> mykvstoreserverpb.KeyValue
	3,  // 10: mykvstoreserverpb.Event.prev_kv:type_name -> mykvstoreserverpb.KeyValue
	4,  // 11: mykvstoreserverpb.KV.Put:input_type -> mykvstoreserverpb.PutRequest
	6,  // 12: mykvstoreserverpb.Watch.Watch:input_type -> mykvstoreserverpb.WatchRequest
	5,  // 13: mykvstoreserverpb.KV.Put:output_type -> mykvstoreserverpb.PutResponse
	10, // 14: mykvstoreserverpb.Watch.Watch:output_type -> mykvstoreserverpb.WatchResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	file_rpc_proto_msgTypes[4].OneofWrappers = []any{
		(*WatchRequest_CreateRequest)(nil),
		(*WatchRequest_CancelRequest)(nil),
		(*WatchRequest_ProgressRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
		EnumInfos:         file_rpc_proto_enumTypes,
		MessageInfos:      file_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
