// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: rpc.proto

package mykvstoreserverpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchCreateRequest_FilterType int32

const (
	WatchCreateRequest_NOPUT    WatchCreateRequest_FilterType = 0
	WatchCreateRequest_NODELETE WatchCreateRequest_FilterType = 1
)

// Enum value maps for WatchCreateRequest_FilterType.
var (
	WatchCreateRequest_FilterType_name = map[int32]string{
		0: "NOPUT",
		1: "NODELETE",
	}
	WatchCreateRequest_FilterType_value = map[string]int32{
		"NOPUT":    0,
		"NODELETE": 1,
	}
)

func (x WatchCreateRequest_FilterType) Enum() *WatchCreateRequest_FilterType {
	p := new(WatchCreateRequest_FilterType)
	*p = x
	return p
}

func (x WatchCreateRequest_FilterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchCreateRequest_FilterType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_enumTypes[0].Descriptor()
}

func (WatchCreateRequest_FilterType) Type() protoreflect.EnumType {
	return &file_rpc_proto_enumTypes[0]
}

func (x WatchCreateRequest_FilterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchCreateRequest_FilterType.Descriptor instead.
func (WatchCreateRequest_FilterType) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{5, 0}
}

type Event_EventType int32

const (
	Event_PUT    Event_EventType = 0
	Event_DELETE Event_EventType = 1
)

// Enum value maps for Event_EventType.
var (
	Event_EventType_name = map[int32]string{
		0: "PUT",
		1: "DELETE",
	}
	Event_EventType_value = map[string]int32{
		"PUT":    0,
		"DELETE": 1,
	}
)

func (x Event_EventType) Enum() *Event_EventType {
	p := new(Event_EventType)
	*p = x
	return p
}

func (x Event_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_enumTypes[1].Descriptor()
}

func (Event_EventType) Type() protoreflect.EnumType {
	return &file_rpc_proto_enumTypes[1]
}

func (x Event_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_EventType.Descriptor instead.
func (Event_EventType) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{9, 0}
}

type RangeRequest_SortOrder int32

const (
	RangeRequest_NONE    RangeRequest_SortOrder = 0
	RangeRequest_ASCEND  RangeRequest_SortOrder = 1
	RangeRequest_DESCEND RangeRequest_SortOrder = 2
)

// Enum value maps for RangeRequest_SortOrder.
var (
	RangeRequest_SortOrder_name = map[int32]string{
		0: "NONE",
		1: "ASCEND",
		2: "DESCEND",
	}
	RangeRequest_SortOrder_value = map[string]int32{
		"NONE":    0,
		"ASCEND":  1,
		"DESCEND": 2,
	}
)

func (x RangeRequest_SortOrder) Enum() *RangeRequest_SortOrder {
	p := new(RangeRequest_SortOrder)
	*p = x
	return p
}

func (x RangeRequest_SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RangeRequest_SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_enumTypes[2].Descriptor()
}

func (RangeRequest_SortOrder) Type() protoreflect.EnumType {
	return &file_rpc_proto_enumTypes[2]
}

func (x RangeRequest_SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RangeRequest_SortOrder.Descriptor instead.
func (RangeRequest_SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{10, 0}
}

type RangeRequest_SortTarget int32

const (
	RangeRequest_KEY     RangeRequest_SortTarget = 0
	RangeRequest_VERSION RangeRequest_SortTarget = 1
	RangeRequest_CREATE  RangeRequest_SortTarget = 2
	RangeRequest_MOD     RangeRequest_SortTarget = 3
	RangeRequest_VALUE   RangeRequest_SortTarget = 4
)

// Enum value maps for RangeRequest_SortTarget.
var (
	RangeRequest_SortTarget_name = map[int32]string{
		0: "KEY",
		1: "VERSION",
		2: "CREATE",
		3: "MOD",
		4: "VALUE",
	}
	RangeRequest_SortTarget_value = map[string]int32{
		"KEY":     0,
		"VERSION": 1,
		"CREATE":  2,
		"MOD":     3,
		"VALUE":   4,
	}
)

func (x RangeRequest_SortTarget) Enum() *RangeRequest_SortTarget {
	p := new(RangeRequest_SortTarget)
	*p = x
	return p
}

func (x RangeRequest_SortTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RangeRequest_SortTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_proto_enumTypes[3].Descriptor()
}

func (RangeRequest_SortTarget) Type() protoreflect.EnumType {
	return &file_rpc_proto_enumTypes[3]
}

func (x RangeRequest_SortTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RangeRequest_SortTarget.Descriptor instead.
func (RangeRequest_SortTarget) EnumDescriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{10, 1}
}

type ResponseHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     uint64                 `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	MemberId      uint64                 `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Revision      int64                  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	RaftTerm      int64                  `protobuf:"varint,4,opt,name=raft_term,json=raftTerm,proto3" json:"raft_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	mi := &file_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseHeader) GetClusterId() uint64 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *ResponseHeader) GetMemberId() uint64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *ResponseHeader) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ResponseHeader) GetRaftTerm() int64 {
	if x != nil {
		return x.RaftTerm
	}
	return 0
}

type KeyValue struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	CreateRevision int64                  `protobuf:"varint,2,opt,name=create_revision,json=createRevision,proto3" json:"create_revision,omitempty"`
	ModRevision    int64                  `protobuf:"varint,3,opt,name=mod_revision,json=modRevision,proto3" json:"mod_revision,omitempty"`
	Version        int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Value          []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Lease          int64                  `protobuf:"varint,6,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *KeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValue) GetCreateRevision() int64 {
	if x != nil {
		return x.CreateRevision
	}
	return 0
}

func (x *KeyValue) GetModRevision() int64 {
	if x != nil {
		return x.ModRevision
	}
	return 0
}

func (x *KeyValue) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyValue) GetLease() int64 {
	if x != nil {
		return x.Lease
	}
	return 0
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	PrevKv        bool                   `protobuf:"varint,4,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"`
	Lease         int64                  `protobuf:"varint,5,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetPrevKv() bool {
	if x != nil {
		return x.PrevKv
	}
	return false
}

func (x *PutRequest) GetLease() int64 {
	if x != nil {
		return x.Lease
	}
	return 0
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	PrevKv        *KeyValue              `protobuf:"bytes,2,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *PutResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PutResponse) GetPrevKv() *KeyValue {
	if x != nil {
		return x.PrevKv
	}
	return nil
}

type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestUnion:
	//
	//	*WatchRequest_CreateRequest
	//	*WatchRequest_CancelRequest
	//	*WatchRequest_ProgressRequest
	RequestUnion  isWatchRequest_RequestUnion `protobuf_oneof:"request_union"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *WatchRequest) GetRequestUnion() isWatchRequest_RequestUnion {
	if x != nil {
		return x.RequestUnion
	}
	return nil
}

func (x *WatchRequest) GetCreateRequest() *WatchCreateRequest {
	if x != nil {
		if x, ok := x.RequestUnion.(*WatchRequest_CreateRequest); ok {
			return x.CreateRequest
		}
	}
	return nil
}

func (x *WatchRequest) GetCancelRequest() *WatchCancelRequest {
	if x != nil {
		if x, ok := x.RequestUnion.(*WatchRequest_CancelRequest); ok {
			return x.CancelRequest
		}
	}
	return nil
}

func (x *WatchRequest) GetProgressRequest() *WatchProgressRequest {
	if x != nil {
		if x, ok := x.RequestUnion.(*WatchRequest_ProgressRequest); ok {
			return x.ProgressRequest
		}
	}
	return nil
}

type isWatchRequest_RequestUnion interface {
	isWatchRequest_RequestUnion()
}

type WatchRequest_CreateRequest struct {
	CreateRequest *WatchCreateRequest `protobuf:"bytes,1,opt,name=create_request,json=createRequest,proto3,oneof"`
}

type WatchRequest_CancelRequest struct {
	CancelRequest *WatchCancelRequest `protobuf:"bytes,2,opt,name=cancel_request,json=cancelRequest,proto3,oneof"`
}

type WatchRequest_ProgressRequest struct {
	ProgressRequest *WatchProgressRequest `protobuf:"bytes,3,opt,name=progress_request,json=progressRequest,proto3,oneof"`
}

func (*WatchRequest_CreateRequest) isWatchRequest_RequestUnion() {}

func (*WatchRequest_CancelRequest) isWatchRequest_RequestUnion() {}

func (*WatchRequest_ProgressRequest) isWatchRequest_RequestUnion() {}

type WatchCreateRequest struct {
	state          protoimpl.MessageState          `protogen:"open.v1"`
	Key            []byte                          `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RangeEnd       []byte                          `protobuf:"bytes,2,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	StartRevision  int64                           `protobuf:"varint,3,opt,name=start_revision,json=startRevision,proto3" json:"start_revision,omitempty"`
	ProgressNotify bool                            `protobuf:"varint,4,opt,name=progress_notify,json=progressNotify,proto3" json:"progress_notify,omitempty"`
	Filters        []WatchCreateRequest_FilterType `protobuf:"varint,5,rep,packed,name=filters,proto3,enum=mykvstoreserverpb.WatchCreateRequest_FilterType" json:"filters,omitempty"`
	PrevKv         bool                            `protobuf:"varint,6,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"`
	WatchId        int64                           `protobuf:"varint,7,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	Fragment       bool                            `protobuf:"varint,8,opt,name=fragment,proto3" json:"fragment,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchCreateRequest) Reset() {
	*x = WatchCreateRequest{}
	mi := &file_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCreateRequest) ProtoMessage() {}

func (x *WatchCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCreateRequest.ProtoReflect.Descriptor instead.
func (*WatchCreateRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *WatchCreateRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *WatchCreateRequest) GetRangeEnd() []byte {
	if x != nil {
		return x.RangeEnd
	}
	return nil
}

func (x *WatchCreateRequest) GetStartRevision() int64 {
	if x != nil {
		return x.StartRevision
	}
	return 0
}

func (x *WatchCreateRequest) GetProgressNotify() bool {
	if x != nil {
		return x.ProgressNotify
	}
	return false
}

func (x *WatchCreateRequest) GetFilters() []WatchCreateRequest_FilterType {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *WatchCreateRequest) GetPrevKv() bool {
	if x != nil {
		return x.PrevKv
	}
	return false
}

func (x *WatchCreateRequest) GetWatchId() int64 {
	if x != nil {
		return x.WatchId
	}
	return 0
}

func (x *WatchCreateRequest) GetFragment() bool {
	if x != nil {
		return x.Fragment
	}
	return false
}

type WatchCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WatchId       int64                  `protobuf:"varint,1,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchCancelRequest) Reset() {
	*x = WatchCancelRequest{}
	mi := &file_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCancelRequest) ProtoMessage() {}

func (x *WatchCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCancelRequest.ProtoReflect.Descriptor instead.
func (*WatchCancelRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *WatchCancelRequest) GetWatchId() int64 {
	if x != nil {
		return x.WatchId
	}
	return 0
}

type WatchProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchProgressRequest) Reset() {
	*x = WatchProgressRequest{}
	mi := &file_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchProgressRequest) ProtoMessage() {}

func (x *WatchProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchProgressRequest.ProtoReflect.Descriptor instead.
func (*WatchProgressRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{7}
}

type WatchResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Header          *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	WatchId         int64                  `protobuf:"varint,2,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	Created         bool                   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Canceled        bool                   `protobuf:"varint,4,opt,name=canceled,proto3" json:"canceled,omitempty"`
	CompactRevision int64                  `protobuf:"varint,5,opt,name=compact_revision,json=compactRevision,proto3" json:"compact_revision,omitempty"`
	CancelReason    string                 `protobuf:"bytes,6,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
	Fragment        bool                   `protobuf:"varint,7,opt,name=fragment,proto3" json:"fragment,omitempty"`
	Events          []*Event               `protobuf:"bytes,8,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *WatchResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *WatchResponse) GetWatchId() int64 {
	if x != nil {
		return x.WatchId
	}
	return 0
}

func (x *WatchResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *WatchResponse) GetCanceled() bool {
	if x != nil {
		return x.Canceled
	}
	return false
}

func (x *WatchResponse) GetCompactRevision() int64 {
	if x != nil {
		return x.CompactRevision
	}
	return 0
}

func (x *WatchResponse) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

func (x *WatchResponse) GetFragment() bool {
	if x != nil {
		return x.Fragment
	}
	return false
}

func (x *WatchResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Event_EventType        `protobuf:"varint,1,opt,name=type,proto3,enum=mykvstoreserverpb.Event_EventType" json:"type,omitempty"`
	Kv            *KeyValue              `protobuf:"bytes,2,opt,name=kv,proto3" json:"kv,omitempty"`
	PrevKv        *KeyValue              `protobuf:"bytes,3,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *Event) GetType() Event_EventType {
	if x != nil {
		return x.Type
	}
	return Event_PUT
}

func (x *Event) GetKv() *KeyValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

func (x *Event) GetPrevKv() *KeyValue {
	if x != nil {
		return x.PrevKv
	}
	return nil
}

type RangeRequest struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	Key               []byte                  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RangeEnd          []byte                  `protobuf:"bytes,2,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	Limit             int64                   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Revision          int64                   `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	SortOrder         RangeRequest_SortOrder  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3,enum=mykvstoreserverpb.RangeRequest_SortOrder" json:"sort_order,omitempty"`
	SortTarget        RangeRequest_SortTarget `protobuf:"varint,6,opt,name=sort_target,json=sortTarget,proto3,enum=mykvstoreserverpb.RangeRequest_SortTarget" json:"sort_target,omitempty"`
	Serializable      bool                    `protobuf:"varint,7,opt,name=serializable,proto3" json:"serializable,omitempty"`
	KeysOnly          bool                    `protobuf:"varint,8,opt,name=keys_only,json=keysOnly,proto3" json:"keys_only,omitempty"`
	CountOnly         bool                    `protobuf:"varint,9,opt,name=count_only,json=countOnly,proto3" json:"count_only,omitempty"`
	MinModRevision    int64                   `protobuf:"varint,10,opt,name=min_mod_revision,json=minModRevision,proto3" json:"min_mod_revision,omitempty"`
	MaxModRevision    int64                   `protobuf:"varint,11,opt,name=max_mod_revision,json=maxModRevision,proto3" json:"max_mod_revision,omitempty"`
	MinCreateRevision int64                   `protobuf:"varint,12,opt,name=min_create_revision,json=minCreateRevision,proto3" json:"min_create_revision,omitempty"`
	MaxCreateRevision int64                   `protobuf:"varint,13,opt,name=max_create_revision,json=maxCreateRevision,proto3" json:"max_create_revision,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RangeRequest) Reset() {
	*x = RangeRequest{}
	mi := &file_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeRequest) ProtoMessage() {}

func (x *RangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeRequest.ProtoReflect.Descriptor instead.
func (*RangeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *RangeRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RangeRequest) GetRangeEnd() []byte {
	if x != nil {
		return x.RangeEnd
	}
	return nil
}

func (x *RangeRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RangeRequest) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *RangeRequest) GetSortOrder() RangeRequest_SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return RangeRequest_NONE
}

func (x *RangeRequest) GetSortTarget() RangeRequest_SortTarget {
	if x != nil {
		return x.SortTarget
	}
	return RangeRequest_KEY
}

func (x *RangeRequest) GetSerializable() bool {
	if x != nil {
		return x.Serializable
	}
	return false
}

func (x *RangeRequest) GetKeysOnly() bool {
	if x != nil {
		return x.KeysOnly
	}
	return false
}

func (x *RangeRequest) GetCountOnly() bool {
	if x != nil {
		return x.CountOnly
	}
	return false
}

func (x *RangeRequest) GetMinModRevision() int64 {
	if x != nil {
		return x.MinModRevision
	}
	return 0
}

func (x *RangeRequest) GetMaxModRevision() int64 {
	if x != nil {
		return x.MaxModRevision
	}
	return 0
}

func (x *RangeRequest) GetMinCreateRevision() int64 {
	if x != nil {
		return x.MinCreateRevision
	}
	return 0
}

func (x *RangeRequest) GetMaxCreateRevision() int64 {
	if x != nil {
		return x.MaxCreateRevision
	}
	return 0
}

type RangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Kvs           []*KeyValue            `protobuf:"bytes,2,rep,name=kvs,proto3" json:"kvs,omitempty"`
	More          bool                   `protobuf:"varint,3,opt,name=more,proto3" json:"more,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeResponse) Reset() {
	*x = RangeResponse{}
	mi := &file_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeResponse) ProtoMessage() {}

func (x *RangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeResponse.ProtoReflect.Descriptor instead.
func (*RangeResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *RangeResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RangeResponse) GetKvs() []*KeyValue {
	if x != nil {
		return x.Kvs
	}
	return nil
}

func (x *RangeResponse) GetMore() bool {
	if x != nil {
		return x.More
	}
	return false
}

func (x *RangeResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DeleteRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RangeEnd      []byte                 `protobuf:"bytes,2,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	PrevKv        bool                   `protobuf:"varint,3,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRangeRequest) Reset() {
	*x = DeleteRangeRequest{}
	mi := &file_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRangeRequest) ProtoMessage() {}

func (x *DeleteRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRangeRequest.ProtoReflect.Descriptor instead.
func (*DeleteRangeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteRangeRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DeleteRangeRequest) GetRangeEnd() []byte {
	if x != nil {
		return x.RangeEnd
	}
	return nil
}

func (x *DeleteRangeRequest) GetPrevKv() bool {
	if x != nil {
		return x.PrevKv
	}
	return false
}

type DeleteRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Deleted       int64                  `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	PrevKvs       []*KeyValue            `protobuf:"bytes,3,rep,name=prev_kvs,json=prevKvs,proto3" json:"prev_kvs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRangeResponse) Reset() {
	*x = DeleteRangeResponse{}
	mi := &file_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRangeResponse) ProtoMessage() {}

func (x *DeleteRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRangeResponse.ProtoReflect.Descriptor instead.
func (*DeleteRangeResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteRangeResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeleteRangeResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *DeleteRangeResponse) GetPrevKvs() []*KeyValue {
	if x != nil {
		return x.PrevKvs
	}
	return nil
}

type CompactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      int64                  `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Physical      bool                   `protobuf:"varint,2,opt,name=physical,proto3" json:"physical,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactionRequest) Reset() {
	*x = CompactionRequest{}
	mi := &file_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactionRequest) ProtoMessage() {}

func (x *CompactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactionRequest.ProtoReflect.Descriptor instead.
func (*CompactionRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *CompactionRequest) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *CompactionRequest) GetPhysical() bool {
	if x != nil {
		return x.Physical
	}
	return false
}

type CompactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactionResponse) Reset() {
	*x = CompactionResponse{}
	mi := &file_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactionResponse) ProtoMessage() {}

func (x *CompactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactionResponse.ProtoReflect.Descriptor instead.
func (*CompactionResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *CompactionResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

var File_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rawDesc = "" +
	"\n" +
	"\trpc.proto\x12\x11mykvstoreserverpb\"\x85\x01\n" +
	"\x0eResponseHeader\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\x04R\tclusterId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\x04R\bmemberId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\x12\x1b\n" +
	"\traft_term\x18\x04 \x01(\x03R\braftTerm\"\xae\x01\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12'\n" +
	"\x0fcreate_revision\x18\x02 \x01(\x03R\x0ecreateRevision\x12!\n" +
	"\fmod_revision\x18\x03 \x01(\x03R\vmodRevision\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\x12\x14\n" +
	"\x05lease\x18\x06 \x01(\x03R\x05lease\"c\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x17\n" +
	"\aprev_kv\x18\x04 \x01(\bR\x06prevKv\x12\x14\n" +
	"\x05lease\x18\x05 \x01(\x03R\x05lease\"~\n" +
	"\vPutResponse\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.mykvstoreserverpb.ResponseHeaderR\x06header\x124\n" +
	"\aprev_kv\x18\x02 \x01(\v2\x1b.mykvstoreserverpb.KeyValueR\x06prevKv\"\x95\x02\n" +
	"\fWatchRequest\x12N\n" +
	"\x0ecreate_request\x18\x01 \x01(\v2%.mykvstoreserverpb.WatchCreateRequestH\x00R\rcreateRequest\x12N\n" +
	"\x0ecancel_request\x18\x02 \x01(\v2%.mykvstoreserverpb.WatchCancelRequestH\x00R\rcancelRequest\x12T\n" +
	"\x10progress_request\x18\x03 \x01(\v2'.mykvstoreserverpb.WatchProgressRequestH\x00R\x0fprogressRequestB\x0f\n" +
	"\rrequest_union\"\xd6\x02\n" +
	"\x12WatchCreateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1b\n" +
	"\trange_end\x18\x02 \x01(\fR\brangeEnd\x12%\n" +
	"\x0estart_revision\x18\x03 \x01(\x03R\rstartRevision\x12'\n" +
	"\x0fprogress_notify\x18\x04 \x01(\bR\x0eprogressNotify\x12J\n" +
	"\afilters\x18\x05 \x03(\x0e20.mykvstoreserverpb.WatchCreateRequest.FilterTypeR\afilters\x12\x17\n" +
	"\aprev_kv\x18\x06 \x01(\bR\x06prevKv\x12\x19\n" +
	"\bwatch_id\x18\a \x01(\x03R\awatchId\x12\x1a\n" +
	"\bfragment\x18\b \x01(\bR\bfragment\"%\n" +
	"\n" +
	"FilterType\x12\t\n" +
	"\x05NOPUT\x10\x00\x12\f\n" +
	"\bNODELETE\x10\x01\"/\n" +
	"\x12WatchCancelRequest\x12\x19\n" +
	"\bwatch_id\x18\x01 \x01(\x03R\awatchId\"\x16\n" +
	"\x14WatchProgressRequest\"\xb9\x02\n" +
	"\rWatchResponse\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.mykvstoreserverpb.ResponseHeaderR\x06header\x12\x19\n" +
	"\bwatch_id\x18\x02 \x01(\x03R\awatchId\x12\x18\n" +
	"\acreated\x18\x03 \x01(\bR\acreated\x12\x1a\n" +
	"\bcanceled\x18\x04 \x01(\bR\bcanceled\x12)\n" +
	"\x10compact_revision\x18\x05 \x01(\x03R\x0fcompactRevision\x12#\n" +
	"\rcancel_reason\x18\x06 \x01(\tR\fcancelReason\x12\x1a\n" +
	"\bfragment\x18\a \x01(\bR\bfragment\x120\n" +
	"\x06events\x18\b \x03(\v2\x18.mykvstoreserverpb.EventR\x06events\"\xc4\x01\n" +
	"\x05Event\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".mykvstoreserverpb.Event.EventTypeR\x04type\x12+\n" +
	"\x02kv\x18\x02 \x01(\v2\x1b.mykvstoreserverpb.KeyValueR\x02kv\x124\n" +
	"\aprev_kv\x18\x03 \x01(\v2\x1b.mykvstoreserverpb.KeyValueR\x06prevKv\" \n" +
	"\tEventType\x12\a\n" +
	"\x03PUT\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01\"\x8e\x05\n" +
	"\fRangeRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1b\n" +
	"\trange_end\x18\x02 \x01(\fR\brangeEnd\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x03R\brevision\x12H\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x0e2).mykvstoreserverpb.RangeRequest.SortOrderR\tsortOrder\x12K\n" +
	"\vsort_target\x18\x06 \x01(\x0e2*.mykvstoreserverpb.RangeRequest.SortTargetR\n" +
	"sortTarget\x12\"\n" +
	"\fserializable\x18\a \x01(\bR\fserializable\x12\x1b\n" +
	"\tkeys_only\x18\b \x01(\bR\bkeysOnly\x12\x1d\n" +
	"\n" +
	"count_only\x18\t \x01(\bR\tcountOnly\x12(\n" +
	"\x10min_mod_revision\x18\n" +
	" \x01(\x03R\x0eminModRevision\x12(\n" +
	"\x10max_mod_revision\x18\v \x01(\x03R\x0emaxModRevision\x12.\n" +
	"\x13min_create_revision\x18\f \x01(\x03R\x11minCreateRevision\x12.\n" +
	"\x13max_create_revision\x18\r \x01(\x03R\x11maxCreateRevision\".\n" +
	"\tSortOrder\x12\b\n" +
	"\x04NONE\x10\x00\x12\n" +
	"\n" +
	"\x06ASCEND\x10\x01\x12\v\n" +
	"\aDESCEND\x10\x02\"B\n" +
	"\n" +
	"SortTarget\x12\a\n" +
	"\x03KEY\x10\x00\x12\v\n" +
	"\aVERSION\x10\x01\x12\n" +
	"\n" +
	"\x06CREATE\x10\x02\x12\a\n" +
	"\x03MOD\x10\x03\x12\t\n" +
	"\x05VALUE\x10\x04\"\xa3\x01\n" +
	"\rRangeResponse\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.mykvstoreserverpb.ResponseHeaderR\x06header\x12-\n" +
	"\x03kvs\x18\x02 \x03(\v2\x1b.mykvstoreserverpb.KeyValueR\x03kvs\x12\x12\n" +
	"\x04more\x18\x03 \x01(\bR\x04more\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\"\\\n" +
	"\x12DeleteRangeRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1b\n" +
	"\trange_end\x18\x02 \x01(\fR\brangeEnd\x12\x17\n" +
	"\aprev_kv\x18\x03 \x01(\bR\x06prevKv\"\xa2\x01\n" +
	"\x13DeleteRangeResponse\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.mykvstoreserverpb.ResponseHeaderR\x06header\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\x03R\adeleted\x126\n" +
	"\bprev_kvs\x18\x03 \x03(\v2\x1b.mykvstoreserverpb.KeyValueR\aprevKvs\"K\n" +
	"\x11CompactionRequest\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\x12\x1a\n" +
	"\bphysical\x18\x02 \x01(\bR\bphysical\"O\n" +
	"\x12CompactionResponse\x129\n" +
	"\x06header\x18\x01 \x01(\v2!.mykvstoreserverpb.ResponseHeaderR\x06header2\xd4\x02\n" +
	"\x02KV\x12L\n" +
	"\x05Range\x12\x1f.mykvstoreserverpb.RangeRequest\x1a .mykvstoreserverpb.RangeResponse\"\x00\x12F\n" +
	"\x03Put\x12\x1d.mykvstoreserverpb.PutRequest\x1a\x1e.mykvstoreserverpb.PutResponse\"\x00\x12^\n" +
	"\vDeleteRange\x12%.mykvstoreserverpb.DeleteRangeRequest\x1a&.mykvstoreserverpb.DeleteRangeResponse\"\x00\x12X\n" +
	"\aCompact\x12$.mykvstoreserverpb.CompactionRequest\x1a%.mykvstoreserverpb.CompactionResponse\"\x002Y\n" +
	"\x05Watch\x12P\n" +
	"\x05Watch\x12\x1f.mykvstoreserverpb.WatchRequest\x1a .mykvstoreserverpb.WatchResponse\"\x00(\x010\x01B\x16Z\x14./;mykvstoreserverpbb\x06proto3"

var (
	file_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rawDescData []byte
)

func file_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)))
	})
	return file_rpc_proto_rawDescData
}

var file_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_rpc_proto_goTypes = []any{
	(WatchCreateRequest_FilterType)(0), // 0: mykvstoreserverpb.WatchCreateRequest.FilterType
	(Event_EventType)(0),               // 1: mykvstoreserverpb.Event.EventType
	(RangeRequest_SortOrder)(0),        // 2: mykvstoreserverpb.RangeRequest.SortOrder
	(RangeRequest_SortTarget)(0),       // 3: mykvstoreserverpb.RangeRequest.SortTarget
	(*ResponseHeader)(nil),             // 4: mykvstoreserverpb.ResponseHeader
	(*KeyValue)(nil),                   // 5: mykvstoreserverpb.KeyValue
	(*PutRequest)(nil),                 // 6: mykvstoreserverpb.PutRequest
	(*PutResponse)(nil),                // 7: mykvstoreserverpb.PutResponse
	(*WatchRequest)(nil),               // 8: mykvstoreserverpb.WatchRequest
	(*WatchCreateRequest)(nil),         // 9: mykvstoreserverpb.WatchCreateRequest
	(*WatchCancelRequest)(nil),         // 10: mykvstoreserverpb.WatchCancelRequest
	(*WatchProgressRequest)(nil),       // 11: mykvstoreserverpb.WatchProgressRequest
	(*WatchResponse)(nil),              // 12: mykvstoreserverpb.WatchResponse
	(*Event)(nil),                      // 13: mykvstoreserverpb.Event
	(*RangeRequest)(nil),               // 14: mykvstoreserverpb.RangeRequest
	(*RangeResponse)(nil),              // 15: mykvstoreserverpb.RangeResponse
	(*DeleteRangeRequest)(nil),         // 16: mykvstoreserverpb.DeleteRangeRequest
	(*DeleteRangeResponse)(nil),        // 17: mykvstoreserverpb.DeleteRangeResponse
	(*CompactionRequest)(nil),          // 18: mykvstoreserverpb.CompactionRequest
	(*CompactionResponse)(nil),         // 19: mykvstoreserverpb.CompactionResponse
}
var file_rpc_proto_depIdxs = []int32{
	4,  // 0: mykvstoreserverpb.PutResponse.header:type_name -> mykvstoreserverpb.ResponseHeader
	5,  // 1: mykvstoreserverpb.PutResponse.prev_kv:type_name -> mykvstoreserverpb.KeyValue
	9,  // 2: mykvstoreserverpb.WatchRequest.create_request:type_name -> mykvstoreserverpb.WatchCreateRequest
	10, // 3: mykvstoreserverpb.WatchRequest.cancel_request:type_name -> mykvstoreserverpb.WatchCancelRequest
	11, // 4: mykvstoreserverpb.WatchRequest.progress_request:type_name -> mykvstoreserverpb.WatchProgressRequest
	0,  // 5: mykvstoreserverpb.WatchCreateRequest.filters:type_name -> mykvstoreserverpb.WatchCreateRequest.FilterType
	4,  // 6: mykvstoreserverpb.WatchResponse.header:type_name -> mykvstoreserverpb.ResponseHeader
	13, // 7: mykvstoreserverpb.WatchResponse.events:type_name -> mykvstoreserverpb.Event
	1,  // 8: mykvstoreserverpb.Event.type:type_name -> mykvstoreserverpb.Event.EventType
	5,  // 9: mykvstoreserverpb.Event.kv:type_name -> mykvstoreserverpb.KeyValue
	5,  // 10: mykvstoreserverpb.Event.prev_kv:type_name -> mykvstoreserverpb.KeyValue
	2,  // 11: mykvstoreserverpb.RangeRequest.sort_order:type_name -> mykvstoreserverpb.RangeRequest.SortOrder
	3,  // 12: mykvstoreserverpb.RangeRequest.sort_target:type_name -> mykvstoreserverpb.RangeRequest.SortTarget
	4,  // 13: mykvstoreserverpb.RangeResponse.header:type_name -> mykvstoreserverpb.ResponseHeader
	5,  // 14: mykvstoreserverpb.RangeResponse.kvs:type_name -> mykvstoreserverpb.KeyValue
	4,  // 15: mykvstoreserverpb.DeleteRangeResponse.header:type_name -> mykvstoreserverpb.ResponseHeader
	5,  // 16: mykvstoreserverpb.DeleteRangeResponse.prev_kvs:type_name -> mykvstoreserverpb.KeyValue
	4,  // 17: mykvstoreserverpb.CompactionResponse.header:type_name -> mykvstoreserverpb.ResponseHeader
	14, // 18: mykvstoreserverpb.KV.Range:input_type -> mykvstoreserverpb.RangeRequest
	6,  // 19: mykvstoreserverpb.KV.Put:input_type -> mykvstoreserverpb.PutRequest
	16, // 20: mykvstoreserverpb.KV.DeleteRange:input_type -> mykvstoreserverpb.DeleteRangeRequest
	18, // 21: mykvstoreserverpb.KV.Compact:input_type -> mykvstoreserverpb.CompactionRequest
	8,  // 22: mykvstoreserverpb.Watch.Watch:input_type -> mykvstoreserverpb.WatchRequest
	15, // 23: mykvstoreserverpb.KV.Range:output_type -> mykvstoreserverpb.RangeResponse
	7,  // 24: mykvstoreserverpb.KV.Put:output_type -> mykvstoreserverpb.PutResponse
	17, // 25: mykvstoreserverpb.KV.DeleteRange:output_type -> mykvstoreserverpb.DeleteRangeResponse
	19, // 26: mykvstoreserverpb.KV.Compact:output_type -> mykvstoreserverpb.CompactionResponse
	12, // 27: mykvstoreserverpb.Watch.Watch:output_type -> mykvstoreserverpb.WatchResponse
	23, // [23:28] is the sub-list for method output_type
	18, // [18:23] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	file_rpc_proto_msgTypes[4].OneofWrappers = []any{
		(*WatchRequest_CreateRequest)(nil),
		(*WatchRequest_CancelRequest)(nil),
		(*WatchRequest_ProgressRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
		EnumInfos:         file_rpc_proto_enumTypes,
		MessageInfos:      file_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
